### ISSUE TITLE
problem with e-internationalization

### ISSUE THREAD

**Issue by bjdmeest** [freme-project/e-services#12]
following command fails

`curl -X POST --header "Content-Type: text/html" --header "Accept: text/html" -d "<p>Dissident Chinese artist Ai Weiwei has been refused a six-month visa by the British government amid claims he lied on his visa application form. Ai posted a letter on Instagram stating his entry to the UK had been restricted because he failed to declare his \"criminal conviction\". But Ai, though detained in China for 81 days in 2011, has never been charged or convicted of a crime in China. The artist was granted a 20-day visa to attend the opening of his London show.</p>" "http://api.freme-project.eu/0.6/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all"`

**Comment by jnehring** [comment]
I can reproduce the problem. The error message is 

```
{
    "timestamp": 1462358240982,
    "status": 500,
    "error": "Internal Server Error",
    "exception": "org.apache.jena.riot.RiotException",
    "message": "[line: 2, col: 13] Triples not terminated by DOT",
    "path": "/e-entity/freme-ner/documents"
}
```

I think the problem originates from e-internationalization and HTML roundtripping because it works when I set "Accept: text/turtle".

We will check if the problem originates from the e-Internationalisation filter or from the underlying e-Internationalization API. When it originates from the filter, we can fix it. Otherwise we need to wait for a new e-internationalization developer.

@ArneBinder please check this.

**Comment by jnehring** [comment]
I fixed the bug through a configuration change in the broker. e-Internationalisation was executed twice, once in the broker and once in freme-ner. So I added the freme-ner endpoint to the e-internationalisation blacklist on the broker.

@bjdmeest please verify that the problem is fixed and close the issue if it is ok now.

**Comment by bjdmeest** [comment]
Fixed, thanks!
