### ISSUE TITLE
[e-link] throws BadRequest randomly

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/e-services#22]
moved from https://github.com/freme-project/e-services/issues/15#issuecomment-229026166
> It seems to be HttpException: 502. I think we should return sth more meaningful than BadRequestException("It seems your SPARQL template is not correctly defined.").

Furthermore we should examine when this happens and what causes the 502.

**Comment by ArneBinder** [comment]
@m1ci any ideas what could cause the 502?

**Comment by m1ci** [comment]
It seems to be caused by one of these lines:

https://github.com/freme-project/e-services/blob/master/e-link/src/main/java/eu/freme/eservices/elink/api/DataEnricher.java#L80

https://github.com/freme-project/e-services/blob/master/e-link/src/main/java/eu/freme/eservices/elink/api/DataEnricher.java#L180

**Comment by ArneBinder** [comment]
I can not reproduce this anymore but will change the error message when I'm back in office.

**Comment by jnehring** [comment]
When the external API returns 502, then FREME should return 502 also. Together with an error message "The remote triple store could not be reached.". @ArneBinder please implement

**Comment by ArneBinder** [comment]
Implemented.
